# Generated by Django 2.2.4 on 2020-02-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(blank=True, db_index=True, max_length=50)),
                ('menu_name', models.CharField(blank=True, db_index=True, max_length=50)),
                ('price', models.SmallIntegerField(blank=True, default=0)),
                ('menu_image', models.ImageField(blank=True, null=True, upload_to='menu/%Y/%m/')),
                ('discount_price', models.SmallIntegerField(blank=True, default=0)),
                ('description', models.CharField(blank=True, db_index=True, max_length=50)),
            ],
        ),
    ]
