# Generated by Django 2.2.4 on 2020-02-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
    ]
