# Generated by Django 2.2.4 on 2020-03-10 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0002_menu_is_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='material',
            field=models.ManyToManyField(to='stock.Stock'),
        ),
        migrations.AddField(
            model_name='menu',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
