# Generated by Django 2.2.4 on 2020-04-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_menu_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='material_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
