# Generated by Django 2.2.4 on 2020-04-23 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('menu', '0005_menu_material_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='material',
        ),
        migrations.AddField(
            model_name='menu',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Stock'),
        ),
    ]
