# Generated by Django 2.2.4 on 2019-09-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='code2',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_force_reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
