# Generated by Django 2.2.4 on 2020-03-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='position',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
