# Generated by Django 2.2.4 on 2020-01-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='point',
            field=models.SmallIntegerField(default=0, max_length=125),
        ),
    ]
