# Generated by Django 2.2.4 on 2019-10-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190919_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='code2',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_force_reset_password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='level_group',
        ),
        migrations.RemoveField(
            model_name='account',
            name='level_name',
        ),
        migrations.AddField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
