# Generated by Django 2.2.4 on 2020-03-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200317_2229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
