# Generated by Django 2.2.4 on 2020-03-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
