# Generated by Django 2.2.4 on 2020-02-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200211_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenu',
            name='service_charge',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermenu',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ordermenu',
            name='vat',
            field=models.FloatField(default=0),
        ),
    ]
