# Generated by Django 2.2.4 on 2020-02-26 17:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False)),
                ('is_confirm', models.BooleanField(default=True)),
                ('service_charge', models.SmallIntegerField(default=0)),
                ('vat', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('food_menu', models.ManyToManyField(to='menu.Menu')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
