# Generated by Django 2.2.4 on 2020-03-17 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='order',
        ),
    ]
