# Generated by Django 2.2.4 on 2020-03-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0002_remove_mycart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='food_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
        ),
    ]
