# Generated by Django 2.2.4 on 2020-04-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0003_auto_20200320_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='is_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='my_cart',
            field=models.ManyToManyField(to='mycart.MyCart'),
        ),
    ]
