# Generated by Django 2.2.4 on 2020-04-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0006_auto_20200425_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='my_cart',
            field=models.ManyToManyField(blank=True, null=True, to='mycart.MyCart'),
        ),
    ]
