# Generated by Django 2.2.4 on 2020-04-26 09:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20200423_2341'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycart', '0007_auto_20200425_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCartTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0)),
                ('datetime_create', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False)),
                ('datetime_update', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_create', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False)),
                ('vat', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('food_menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu')),
                ('my_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycart.MyCartTest')),
            ],
        ),
    ]
