# Generated by Django 2.2.4 on 2020-04-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0008_mycarttest_ordertest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycarttest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordertest',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordertest',
            name='vat',
            field=models.FloatField(default=0.7),
        ),
    ]
