# Generated by Django 2.2.4 on 2020-04-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0010_ordertest_is_confirm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycarttest',
            old_name='is_paid',
            new_name='is_confirm',
        ),
        migrations.RenameField(
            model_name='ordertest',
            old_name='is_confirm',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='mycarttest',
            name='user',
        ),
    ]
