# Generated by Django 2.2.4 on 2020-04-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0011_auto_20200426_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertest',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='ordertest',
            name='total',
        ),
        migrations.RemoveField(
            model_name='ordertest',
            name='vat',
        ),
    ]
