# Generated by Django 2.2.4 on 2020-04-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0012_auto_20200426_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='my_cart',
            field=models.ManyToManyField(to='mycart.MyCart'),
        ),
    ]
