# Generated by Django 2.2.4 on 2020-02-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='promotion_order',
            field=models.ManyToManyField(to='menu.Menu'),
        ),
    ]
