# Generated by Django 2.2.4 on 2020-04-23 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20200423_2341'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotions',
            name='promotion_order',
        ),
        migrations.AddField(
            model_name='promotions',
            name='promotion_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
        ),
    ]
