# Generated by Django 2.2.4 on 2020-02-26 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(default=1)),
                ('queue', models.IntegerField(default=1)),
                ('is_confirm', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False)),
                ('count', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
