# Generated by Django 2.2.4 on 2020-02-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='count',
            field=models.SmallIntegerField(default=1),
        ),
    ]
