# Generated by Django 2.2.4 on 2020-02-11 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
