# Generated by Django 2.2.4 on 2020-04-24 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='count',
        ),
    ]
